### ISSUE TITLE
Unable to Find parse_nanopolish_entropy.pl Script

### ISSUE THREAD

**Issue by priyankagaikwad2208** [Lab-CoMBINE/PoreMeth2#1]
I can't find the parse_nanopolish_entropy.pl script mentioned in your project's documentation. Could you let me know where I can download or access this script?
Thank you.

**Comment by Congnguyenn** [comment]
Same issue, could you please provide the parse_nanopolish_entropy.pl?
Thank you

**Comment by martabaragli** [comment]
Hi,
We uploaded an additional repository containing the scripts for entropy calculation and updated the installation section accordingly. Let us know if you have any trouble.
